spring:
  datasource:
    url: jdbc:mysql://localhost:3306/letstalk?serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
  thymeleaf:
    cache: false
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /css/**,/js/**,/img/**
server:
  port: 7788
