spring:
  datasource:
    url: jdbc:mysql://47.97.222.200:3306/letstalk
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    cache: false
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /css/**,/js/**,/img/**
server:
  port: 7788

